-- Form ID reference registry.
-- One row per unique lead-form id / SKU across the company sites, so the CRM
-- (and the client) can resolve an incoming form id to the page/form that
-- produced it. Non-sensitive reference data: readable with the anon key.
--
-- Generated by scripts/generate-form-ids.mjs. To refresh after adding pages,
-- re-run the generator and apply the updated migration (upserts are idempotent).

create table if not exists public.form_registry (
  form_id       text primary key,
  site          text not null default 'myfence',
  form_type     text not null,
  page_category text,
  page_path     text,
  page_url      text,
  description   text,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

comment on table public.form_registry is
  'Reference table mapping each unique lead-form id/SKU to the page/form it belongs to. Used by the CRM for lead attribution.';

alter table public.form_registry enable row level security;

-- Public read access (reference data only; no PII).
drop policy if exists "form_registry public read" on public.form_registry;
create policy "form_registry public read"
  on public.form_registry
  for select
  to anon, authenticated
  using (true);

insert into public.form_registry
  (form_id, site, form_type, page_category, page_path, page_url, description)
values
  ('MF-SA-BELLEVUE', 'myfence', 'contact', 'service_area_city', '/service-areas/bellevue', 'https://myfence.com/service-areas/bellevue', 'Bellevue (service area) contact form'),
  ('MF-NB-BELLEVUE-NEWCASTLE', 'myfence', 'contact', 'neighborhood', '/service-areas/bellevue/newcastle', 'https://myfence.com/service-areas/bellevue/newcastle', 'Newcastle, Bellevue (neighborhood) contact form'),
  ('MF-NB-BELLEVUE-NEWPORT-HILLS', 'myfence', 'contact', 'neighborhood', '/service-areas/bellevue/newport-hills', 'https://myfence.com/service-areas/bellevue/newport-hills', 'Newport Hills, Bellevue (neighborhood) contact form'),
  ('MF-NB-BELLEVUE-SHERWOOD-FOREST', 'myfence', 'contact', 'neighborhood', '/service-areas/bellevue/sherwood-forest', 'https://myfence.com/service-areas/bellevue/sherwood-forest', 'Sherwood Forest, Bellevue (neighborhood) contact form'),
  ('MF-NB-BELLEVUE-SOMERSET', 'myfence', 'contact', 'neighborhood', '/service-areas/bellevue/somerset', 'https://myfence.com/service-areas/bellevue/somerset', 'Somerset, Bellevue (neighborhood) contact form'),
  ('MF-SA-BLACK-DIAMOND', 'myfence', 'contact', 'service_area_city', '/service-areas/black-diamond', 'https://myfence.com/service-areas/black-diamond', 'Black Diamond (service area) contact form'),
  ('MF-NB-BLACK-DIAMOND-LAWSON-HILL-ESTATES', 'myfence', 'contact', 'neighborhood', '/service-areas/black-diamond/lawson-hill-estates', 'https://myfence.com/service-areas/black-diamond/lawson-hill-estates', 'Lawson Hill Estates, Black Diamond (neighborhood) contact form'),
  ('MF-SA-BONNEY-LAKE', 'myfence', 'contact', 'service_area_city', '/service-areas/bonney-lake', 'https://myfence.com/service-areas/bonney-lake', 'Bonney Lake (service area) contact form'),
  ('MF-NB-BONNEY-LAKE-DOWNTOWN-BONNEY-LAKE', 'myfence', 'contact', 'neighborhood', '/service-areas/bonney-lake/downtown-bonney-lake', 'https://myfence.com/service-areas/bonney-lake/downtown-bonney-lake', 'Downtown Bonney Lake, Bonney Lake (neighborhood) contact form'),
  ('MF-NB-BONNEY-LAKE-FALLING-WATER', 'myfence', 'contact', 'neighborhood', '/service-areas/bonney-lake/falling-water', 'https://myfence.com/service-areas/bonney-lake/falling-water', 'Falling Water, Bonney Lake (neighborhood) contact form'),
  ('MF-NB-BONNEY-LAKE-LAKE-TAPPS', 'myfence', 'contact', 'neighborhood', '/service-areas/bonney-lake/lake-tapps', 'https://myfence.com/service-areas/bonney-lake/lake-tapps', 'Lake Tapps, Bonney Lake (neighborhood) contact form'),
  ('MF-NB-BONNEY-LAKE-LOWER-TEHALEH', 'myfence', 'contact', 'neighborhood', '/service-areas/bonney-lake/lower-tehaleh', 'https://myfence.com/service-areas/bonney-lake/lower-tehaleh', 'Lower Tehaleh, Bonney Lake (neighborhood) contact form'),
  ('MF-NB-BONNEY-LAKE-MOUNTAIN-CREEK', 'myfence', 'contact', 'neighborhood', '/service-areas/bonney-lake/mountain-creek', 'https://myfence.com/service-areas/bonney-lake/mountain-creek', 'Mountain Creek, Bonney Lake (neighborhood) contact form'),
  ('MF-NB-BONNEY-LAKE-UPPER-TEHALEH', 'myfence', 'contact', 'neighborhood', '/service-areas/bonney-lake/upper-tehaleh', 'https://myfence.com/service-areas/bonney-lake/upper-tehaleh', 'Upper Tehaleh, Bonney Lake (neighborhood) contact form'),
  ('MF-SA-BOTHELL', 'myfence', 'contact', 'service_area_city', '/service-areas/bothell', 'https://myfence.com/service-areas/bothell', 'Bothell (service area) contact form'),
  ('MF-SA-COVINGTON', 'myfence', 'contact', 'service_area_city', '/service-areas/covington', 'https://myfence.com/service-areas/covington', 'Covington (service area) contact form'),
  ('MF-NB-COVINGTON-COVINGTON-WOODS', 'myfence', 'contact', 'neighborhood', '/service-areas/covington/covington-woods', 'https://myfence.com/service-areas/covington/covington-woods', 'Covington Woods, Covington (neighborhood) contact form'),
  ('MF-NB-COVINGTON-LAKE-SAWYER', 'myfence', 'contact', 'neighborhood', '/service-areas/covington/lake-sawyer', 'https://myfence.com/service-areas/covington/lake-sawyer', 'Lake Sawyer, Covington (neighborhood) contact form'),
  ('MF-NB-COVINGTON-MAPLE-HILLS', 'myfence', 'contact', 'neighborhood', '/service-areas/covington/maple-hills', 'https://myfence.com/service-areas/covington/maple-hills', 'Maple Hills, Covington (neighborhood) contact form'),
  ('MF-NB-COVINGTON-TIMBERLANE', 'myfence', 'contact', 'neighborhood', '/service-areas/covington/timberlane', 'https://myfence.com/service-areas/covington/timberlane', 'Timberlane, Covington (neighborhood) contact form'),
  ('MF-SA-ENUMCLAW', 'myfence', 'contact', 'service_area_city', '/service-areas/enumclaw', 'https://myfence.com/service-areas/enumclaw', 'Enumclaw (service area) contact form'),
  ('MF-NB-ENUMCLAW-BUCKLEY', 'myfence', 'contact', 'neighborhood', '/service-areas/enumclaw/buckley', 'https://myfence.com/service-areas/enumclaw/buckley', 'Buckley, Enumclaw (neighborhood) contact form'),
  ('MF-SA-FEDERAL-WAY', 'myfence', 'contact', 'service_area_city', '/service-areas/federal-way', 'https://myfence.com/service-areas/federal-way', 'Federal Way (service area) contact form'),
  ('MF-SA-GIG-HARBOR', 'myfence', 'contact', 'service_area_city', '/service-areas/gig-harbor', 'https://myfence.com/service-areas/gig-harbor', 'Gig Harbor (service area) contact form'),
  ('MF-SA-ISSAQUAH', 'myfence', 'contact', 'service_area_city', '/service-areas/issaquah', 'https://myfence.com/service-areas/issaquah', 'Issaquah (service area) contact form'),
  ('MF-SA-ISSAQUAH-HIGHLANDS', 'myfence', 'contact', 'service_area_city', '/service-areas/issaquah-highlands', 'https://myfence.com/service-areas/issaquah-highlands', 'Issaquah Highlands (service area) contact form'),
  ('MF-NB-ISSAQUAH-MIRRORMONT', 'myfence', 'contact', 'neighborhood', '/service-areas/issaquah/mirrormont', 'https://myfence.com/service-areas/issaquah/mirrormont', 'Mirrormont, Issaquah (neighborhood) contact form'),
  ('MF-SA-KENT', 'myfence', 'contact', 'service_area_city', '/service-areas/kent', 'https://myfence.com/service-areas/kent', 'Kent (service area) contact form'),
  ('MF-NB-KENT-WYNACO', 'myfence', 'contact', 'neighborhood', '/service-areas/kent/wynaco', 'https://myfence.com/service-areas/kent/wynaco', 'Wynaco, Kent (neighborhood) contact form'),
  ('MF-SA-KIRKLAND', 'myfence', 'contact', 'service_area_city', '/service-areas/kirkland', 'https://myfence.com/service-areas/kirkland', 'Kirkland (service area) contact form'),
  ('MF-NB-KIRKLAND-JUANITA', 'myfence', 'contact', 'neighborhood', '/service-areas/kirkland/juanita', 'https://myfence.com/service-areas/kirkland/juanita', 'Juanita, Kirkland (neighborhood) contact form'),
  ('MF-SA-LAKE-TAPPS', 'myfence', 'contact', 'service_area_city', '/service-areas/lake-tapps', 'https://myfence.com/service-areas/lake-tapps', 'Lake Tapps (service area) contact form'),
  ('MF-SA-MAPLE-VALLEY', 'myfence', 'contact', 'service_area_city', '/service-areas/maple-valley', 'https://myfence.com/service-areas/maple-valley', 'Maple Valley (service area) contact form'),
  ('MF-NB-MAPLE-VALLEY-BARKLAY-WOODS', 'myfence', 'contact', 'neighborhood', '/service-areas/maple-valley/barklay-woods', 'https://myfence.com/service-areas/maple-valley/barklay-woods', 'Barklay Woods, Maple Valley (neighborhood) contact form'),
  ('MF-NB-MAPLE-VALLEY-CHEROKEE-BAY-PARK', 'myfence', 'contact', 'neighborhood', '/service-areas/maple-valley/cherokee-bay-park', 'https://myfence.com/service-areas/maple-valley/cherokee-bay-park', 'Cherokee Bay Park, Maple Valley (neighborhood) contact form'),
  ('MF-NB-MAPLE-VALLEY-ELK-RUN', 'myfence', 'contact', 'neighborhood', '/service-areas/maple-valley/elk-run', 'https://myfence.com/service-areas/maple-valley/elk-run', 'Elk Run, Maple Valley (neighborhood) contact form'),
  ('MF-NB-MAPLE-VALLEY-HIGHLANDS-AT-CEDAR-DOWNS', 'myfence', 'contact', 'neighborhood', '/service-areas/maple-valley/highlands-at-cedar-downs', 'https://myfence.com/service-areas/maple-valley/highlands-at-cedar-downs', 'Highlands At Cedar Downs, Maple Valley (neighborhood) contact form'),
  ('MF-NB-MAPLE-VALLEY-LAKE-PARK', 'myfence', 'contact', 'neighborhood', '/service-areas/maple-valley/lake-park', 'https://myfence.com/service-areas/maple-valley/lake-park', 'Lake Park, Maple Valley (neighborhood) contact form'),
  ('MF-NB-MAPLE-VALLEY-MAPLE-WOODS', 'myfence', 'contact', 'neighborhood', '/service-areas/maple-valley/maple-woods', 'https://myfence.com/service-areas/maple-valley/maple-woods', 'Maple Woods, Maple Valley (neighborhood) contact form'),
  ('MF-NB-MAPLE-VALLEY-PATRICKS-FAIRE', 'myfence', 'contact', 'neighborhood', '/service-areas/maple-valley/patricks-faire', 'https://myfence.com/service-areas/maple-valley/patricks-faire', 'Patricks Faire, Maple Valley (neighborhood) contact form'),
  ('MF-NB-MAPLE-VALLEY-RAVENSDALE', 'myfence', 'contact', 'neighborhood', '/service-areas/maple-valley/ravensdale', 'https://myfence.com/service-areas/maple-valley/ravensdale', 'Ravensdale, Maple Valley (neighborhood) contact form'),
  ('MF-SA-MOUNTLAKE-TERRACE', 'myfence', 'contact', 'service_area_city', '/service-areas/mountlake-terrace', 'https://myfence.com/service-areas/mountlake-terrace', 'Mountlake Terrace (service area) contact form'),
  ('MF-SA-NORTH-BEND', 'myfence', 'contact', 'service_area_city', '/service-areas/north-bend', 'https://myfence.com/service-areas/north-bend', 'North Bend (service area) contact form'),
  ('MF-SA-REDMOND', 'myfence', 'contact', 'service_area_city', '/service-areas/redmond', 'https://myfence.com/service-areas/redmond', 'Redmond (service area) contact form'),
  ('MF-SA-RENTON', 'myfence', 'contact', 'service_area_city', '/service-areas/renton', 'https://myfence.com/service-areas/renton', 'Renton (service area) contact form'),
  ('MF-NB-RENTON-KENNYDALE', 'myfence', 'contact', 'neighborhood', '/service-areas/renton/kennydale', 'https://myfence.com/service-areas/renton/kennydale', 'Kennydale, Renton (neighborhood) contact form'),
  ('MF-NB-RENTON-MAPLE-RIDGE-ESTATES', 'myfence', 'contact', 'neighborhood', '/service-areas/renton/maple-ridge-estates', 'https://myfence.com/service-areas/renton/maple-ridge-estates', 'Maple Ridge Estates, Renton (neighborhood) contact form'),
  ('MF-NB-RENTON-MAPLE-VALLEY-HEIGHTS', 'myfence', 'contact', 'neighborhood', '/service-areas/renton/maple-valley-heights', 'https://myfence.com/service-areas/renton/maple-valley-heights', 'Maple Valley Heights, Renton (neighborhood) contact form'),
  ('MF-NB-RENTON-THE-GROVE-AT-SPRING-LAKE', 'myfence', 'contact', 'neighborhood', '/service-areas/renton/the-grove-at-spring-lake', 'https://myfence.com/service-areas/renton/the-grove-at-spring-lake', 'The Grove At Spring Lake, Renton (neighborhood) contact form'),
  ('MF-SA-SAMMAMISH', 'myfence', 'contact', 'service_area_city', '/service-areas/sammamish', 'https://myfence.com/service-areas/sammamish', 'Sammamish (service area) contact form'),
  ('MF-NB-SAMMAMISH-KLAHANIE', 'myfence', 'contact', 'neighborhood', '/service-areas/sammamish/klahanie', 'https://myfence.com/service-areas/sammamish/klahanie', 'Klahanie, Sammamish (neighborhood) contact form'),
  ('MF-SA-SEATAC', 'myfence', 'contact', 'service_area_city', '/service-areas/seatac', 'https://myfence.com/service-areas/seatac', 'Seatac (service area) contact form'),
  ('MF-NB-SEATAC-ANGLE-LAKE', 'myfence', 'contact', 'neighborhood', '/service-areas/seatac/angle-lake', 'https://myfence.com/service-areas/seatac/angle-lake', 'Angle Lake, Seatac (neighborhood) contact form'),
  ('MF-NB-SEATAC-BOW-LAKE', 'myfence', 'contact', 'neighborhood', '/service-areas/seatac/bow-lake', 'https://myfence.com/service-areas/seatac/bow-lake', 'Bow Lake, Seatac (neighborhood) contact form'),
  ('MF-NB-SEATAC-MCMICKEN-HEIGHTS', 'myfence', 'contact', 'neighborhood', '/service-areas/seatac/mcmicken-heights', 'https://myfence.com/service-areas/seatac/mcmicken-heights', 'Mcmicken Heights, Seatac (neighborhood) contact form'),
  ('MF-SA-SEATTLE', 'myfence', 'contact', 'service_area_city', '/service-areas/seattle', 'https://myfence.com/service-areas/seattle', 'Seattle (service area) contact form'),
  ('MF-NB-SEATTLE-RAVENNA', 'myfence', 'contact', 'neighborhood', '/service-areas/seattle/ravenna', 'https://myfence.com/service-areas/seattle/ravenna', 'Ravenna, Seattle (neighborhood) contact form'),
  ('MF-SA-SUMNER', 'myfence', 'contact', 'service_area_city', '/service-areas/sumner', 'https://myfence.com/service-areas/sumner', 'Sumner (service area) contact form'),
  ('MF-SA-TUKWILA', 'myfence', 'contact', 'service_area_city', '/service-areas/tukwila', 'https://myfence.com/service-areas/tukwila', 'Tukwila (service area) contact form'),
  ('MF-SA-UNIVERSITY-PLACE', 'myfence', 'contact', 'service_area_city', '/service-areas/university-place', 'https://myfence.com/service-areas/university-place', 'University Place (service area) contact form'),
  ('MF-NB-UNIVERSITY-PLACE-DEVONSHIRE-TOWNHOMES', 'myfence', 'contact', 'neighborhood', '/service-areas/university-place/devonshire-townhomes', 'https://myfence.com/service-areas/university-place/devonshire-townhomes', 'Devonshire Townhomes, University Place (neighborhood) contact form'),
  ('myfence:home-contact', 'myfence', 'contact', 'named_form', '/', 'https://myfence.com/', 'Home page contact form'),
  ('myfence:inline-contact', 'myfence', 'contact', 'named_form', '/', 'https://myfence.com/', 'Home inline contact section'),
  ('myfence:contact-page', 'myfence', 'contact', 'named_form', '/contact', 'https://myfence.com/contact', 'Contact page'),
  ('myfence:inline-quote', 'myfence', 'quote', 'named_form', '(multiple)', '(multiple)', 'Inline quote form (city pages, etc.)'),
  ('myfence:quote-modal', 'myfence', 'quote', 'named_form', '(global)', '(global)', 'Global quote modal'),
  ('myfence:referral', 'myfence', 'referral', 'named_form', '/referrals', 'https://myfence.com/referrals', 'Referrals page'),
  ('myfence:discount-wheel', 'myfence', 'discount', 'named_form', '/discounts', 'https://myfence.com/discounts', 'Discounts spin-the-wheel'),
  ('myfence:discount-already-played', 'myfence', 'quote', 'named_form', '/discounts', 'https://myfence.com/discounts', 'Discounts (already played)')
on conflict (form_id) do update set
  site          = excluded.site,
  form_type     = excluded.form_type,
  page_category = excluded.page_category,
  page_path     = excluded.page_path,
  page_url      = excluded.page_url,
  description   = excluded.description,
  is_active     = true,
  updated_at    = now();
